name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=default&hide=contribs,issues
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card deepctr
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=readme-tools&repo=deepctr&cache_seconds=18000&theme=default_repocard
          path: profile/deepctr_pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card deepmatch
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=readme-tools&repo=deepmatch&cache_seconds=18000&theme=default_repocard
          path: profile/deepmatch_pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card deepctr-torch
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=readme-tools&repo=deepctr-torch&cache_seconds=18000&theme=default_repocard
          path: profile/deepctr-torch_pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card graphembedding
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=readme-tools&repo=graphembedding&cache_seconds=18000&theme=default_repocard
          path: profile/graphembedding_pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
